config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand"><%= link_to "Alex Owens", root_path %></h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">Alex Owens' Blog</h1>
    <p class="lead blog-description">A Blog that makes Sense.</p>
    <%= link_to 'Write a New Blog', new_blog_path  if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About Me</h4>
    <p>After spending years trying to earn A's and B's in school, I thought it was time to take a risk and <em> learn! </em> I am now a Full Stack Ruby Rails Web Developer that is taking more time to learn than to earn. </p>
  </div>
  
  <div class="sidebar-module">
    <h4><strong>Find Me Elsewhere:</strong></h4>
    <table style="width:100%" class="list-unstyled social-links">
    <tr>
      <td> </td>
    </tr>
    <tr> 
      <td><a href="https://www.linkedin.com/in/alex-r-owens-91085298/" target="_blank"><%= fa_icon "linkedin" %></a></td>
      <td><a href="https://www.facebook.com/alexlink1993" target="_blank"><%= fa_icon "facebook-official" %></a></td>
    </tr>
    <tr>
      <td><a href="https://twitter.com/alexowensdev" target="_blank"><%= fa_icon "twitter" %></a></td>
      <td><a href="https://www.instagram.com/alexrowens/?hl=en" target="_blank"><%= fa_icon "instagram" %> </a></td>
    </tr>
    <tr>
      <td><a href="https://github.com/alexowens12" target="_blank"><%= fa_icon "github" %></a></td>
      <td><a href="https://rubygems.org/profiles/AlexOwens" target="_blank"><%= fa_icon "diamond"%>  </a></td>
    </tr>
    </table>
  </div>
</div> 

app/views/shared/_nav.html.erb
<div class= "<%= location %>"> 
      <%= link_to "Home", root_path %>
      <%= link_to "About", about_me_path %>
      <%= link_to "Contact", contact_path %>
      <%= link_to "Blog", blogs_path %>
      <%= link_to "Portfolio", portfolios_path %>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "All Portfolio Items", portfolios_path %> <strong>|</strong> 
      <a href="#">Back to top</a>
    </p>
    <p>
    <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Alex's Portfolio</h1>
      <p class="lead-text-muted">Here are a series of my works that I have been developing over the last few months.</p>
      <p>
        <%= link_to 'More About Me', about_me_path, class: 'btn btn-primary' %>
        <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
      </p>
    </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About Me</h4>
        <p class="text-muted">After spending years trying to earn A's and B's in school, I thought it was time to take a risk and <em>learn!</em> I am now a Full Stack Ruby Rails Web Developer that is taking the time to learn than to earn.</p>
      </div>
      <div class="col-sm-4 py-4">
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Alex Owens' Portfolio</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>